export interface LeadCandidate {
  companyName: string;
  contactName: string;
  title: string;
  region: string;
  industry: string;
  companySize: string;
  tags: string[];
  traits: string[];
  painPointSignals: string[];
  sourceTemplateKey: string;
}

export const LEAD_POOL: LeadCandidate[] = [
  // SaaS / North America / Mid-Market — high-fit for Clay's ICP
  { companyName: "Ramp", contactName: "Sarah Chen", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["series-c", "outbound-heavy", "high-growth"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Recently raised Series A/B", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Low outbound reply rates", "Pipeline efficiency declining", "Tool sprawl across sales stack"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Notion", contactName: "Marcus Lee", title: "Head of Growth", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["product-led-sales", "expanding-outbound"], traits: ["Uses outbound as primary GTM", "Growing headcount in sales", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["SDR ramp time too long", "Low outbound reply rates"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Lattice", contactName: "Amanda Rodriguez", title: "RevOps Manager", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["hr-tech", "revops-mature", "series-d"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Poor lead-to-opportunity conversion", "Wasted outbound effort on bad-fit accounts", "Tool sprawl across sales stack"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Linear", contactName: "Jason Park", title: "Head of Growth", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["dev-tools", "series-b", "lean-sales"], traits: ["Recently raised Series A/B", "Growing headcount in sales"], painPointSignals: ["Low outbound reply rates", "Pipeline efficiency declining"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Vercel", contactName: "Priya Patel", title: "SDR Manager", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["dev-infra", "outbound-heavy", "series-d"], traits: ["Has SDR team of 5+", "Uses outbound as primary GTM", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["SDR ramp time too long", "Low outbound reply rates", "Wasted outbound effort on bad-fit accounts"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Retool", contactName: "Tom Williams", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["dev-tools", "scaling-sales", "series-c"], traits: ["Uses Salesforce or HubSpot CRM", "Has SDR team of 5+", "Recently raised Series A/B"], painPointSignals: ["Pipeline efficiency declining", "Tool sprawl across sales stack"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Vanta", contactName: "Emily Foster", title: "CRO", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["compliance-saas", "outbound-heavy", "series-b"], traits: ["Recently raised Series A/B", "Uses outbound as primary GTM", "Has SDR team of 5+"], painPointSignals: ["Poor lead-to-opportunity conversion", "Low outbound reply rates"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Deel", contactName: "David Kim", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["hr-tech", "global-sales", "series-d"], traits: ["Uses outbound as primary GTM", "Uses Salesforce or HubSpot CRM", "Growing headcount in sales", "Has SDR team of 5+"], painPointSignals: ["Pipeline efficiency declining", "Tool sprawl across sales stack", "SDR ramp time too long"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Mercury", contactName: "Jennifer Liu", title: "Head of Growth", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["fintech-saas", "series-c", "scaling"], traits: ["Uses Salesforce or HubSpot CRM", "Recently raised Series A/B", "Growing headcount in sales"], painPointSignals: ["Low outbound reply rates", "SDR ramp time too long"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Brex", contactName: "Robert Martinez", title: "VP Revenue Operations", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["fintech", "enterprise-sales", "data-driven"], traits: ["Uses outbound as primary GTM", "Uses Salesforce or HubSpot CRM", "Has SDR team of 5+"], painPointSignals: ["Wasted outbound effort on bad-fit accounts", "Poor lead-to-opportunity conversion"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Rippling", contactName: "Christina Zhao", title: "SDR Manager", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["hr-tech", "outbound-heavy", "series-c"], traits: ["Has SDR team of 5+", "Uses outbound as primary GTM", "Uses Salesforce or HubSpot CRM", "Growing headcount in sales"], painPointSignals: ["SDR ramp time too long", "Low outbound reply rates", "Pipeline efficiency declining"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Figma", contactName: "Alex Thompson", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["design-tools", "enterprise-motion", "high-growth"], traits: ["Uses outbound as primary GTM", "Uses Salesforce or HubSpot CRM", "Growing headcount in sales"], painPointSignals: ["Pipeline efficiency declining", "Tool sprawl across sales stack"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Runway", contactName: "Maria Garcia", title: "Head of Growth", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["ai-tools", "series-c", "expanding-sales"], traits: ["Recently raised Series A/B", "Growing headcount in sales"], painPointSignals: ["Low outbound reply rates", "SDR ramp time too long"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Webflow", contactName: "Brandon Mitchell", title: "CRO", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["no-code", "outbound-motion", "series-c"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Recently raised Series A/B", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Poor lead-to-opportunity conversion", "Pipeline efficiency declining", "Wasted outbound effort on bad-fit accounts"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Loom", contactName: "Laura Bell", title: "RevOps Manager", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["video-tools", "outbound-growing"], traits: ["Uses Salesforce or HubSpot CRM", "Growing headcount in sales", "Uses outbound as primary GTM"], painPointSignals: ["Tool sprawl across sales stack", "Pipeline efficiency declining"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Amplitude", contactName: "Jake Hernandez", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["analytics", "enterprise-sales", "outbound"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Low outbound reply rates", "Wasted outbound effort on bad-fit accounts", "Pipeline efficiency declining"], sourceTemplateKey: "saas-na-mm" },

  // SaaS / North America / Enterprise
  { companyName: "Snowflake", contactName: "Michael Torres", title: "SVP Sales", region: "North America", industry: "SaaS", companySize: "Enterprise", tags: ["data-infra", "enterprise-sales", "public-company"], traits: ["Uses outbound as primary GTM", "Uses Salesforce or HubSpot CRM", "Growing headcount in sales", "Has SDR team of 5+"], painPointSignals: ["Pipeline efficiency declining", "Tool sprawl across sales stack", "SDR ramp time too long"], sourceTemplateKey: "saas-na-ent" },
  { companyName: "Datadog", contactName: "Diana Wright", title: "VP Revenue Operations", region: "North America", industry: "SaaS", companySize: "Enterprise", tags: ["observability", "enterprise-sales", "high-growth"], traits: ["Uses outbound as primary GTM", "Uses Salesforce or HubSpot CRM", "Has SDR team of 5+"], painPointSignals: ["Wasted outbound effort on bad-fit accounts", "Poor lead-to-opportunity conversion", "Tool sprawl across sales stack"], sourceTemplateKey: "saas-na-ent" },
  { companyName: "MongoDB", contactName: "James Patterson", title: "Chief Growth Officer", region: "North America", industry: "SaaS", companySize: "Enterprise", tags: ["database", "developer-tools", "public-company"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM", "Growing headcount in sales"], painPointSignals: ["Pipeline efficiency declining", "SDR ramp time too long"], sourceTemplateKey: "saas-na-ent" },
  { companyName: "Twilio", contactName: "Karen Lee", title: "CRO", region: "North America", industry: "SaaS", companySize: "Enterprise", tags: ["communications", "api-platform", "enterprise"], traits: ["Uses Salesforce or HubSpot CRM", "Has SDR team of 5+", "Uses outbound as primary GTM"], painPointSignals: ["Low outbound reply rates", "Wasted outbound effort on bad-fit accounts"], sourceTemplateKey: "saas-na-ent" },

  // SaaS / Europe / Mid-Market
  { companyName: "Personio", contactName: "Hans Mueller", title: "VP Sales", region: "Europe", industry: "SaaS", companySize: "Mid-Market", tags: ["hr-tech", "eu-expansion", "series-e"], traits: ["Uses outbound as primary GTM", "Recently raised Series A/B", "Has SDR team of 5+"], painPointSignals: ["Low outbound reply rates", "Pipeline efficiency declining", "SDR ramp time too long"], sourceTemplateKey: "saas-eu-mm" },
  { companyName: "Paddle", contactName: "Sofia Andersson", title: "Head of Growth", region: "Europe", industry: "SaaS", companySize: "Mid-Market", tags: ["payments", "series-d", "saas-billing"], traits: ["Growing headcount in sales", "Recently raised Series A/B", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Poor lead-to-opportunity conversion", "SDR ramp time too long"], sourceTemplateKey: "saas-eu-mm" },
  { companyName: "ContentSquare", contactName: "Pierre Laurent", title: "CRO", region: "Europe", industry: "SaaS", companySize: "Mid-Market", tags: ["analytics", "enterprise-motion", "series-e"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Pipeline efficiency declining", "Tool sprawl across sales stack", "Wasted outbound effort on bad-fit accounts"], sourceTemplateKey: "saas-eu-mm" },
  { companyName: "Miro", contactName: "Anna Kowalski", title: "VP Sales", region: "Europe", industry: "SaaS", companySize: "Mid-Market", tags: ["collaboration", "product-led-sales", "high-growth"], traits: ["Uses outbound as primary GTM", "Growing headcount in sales", "Has SDR team of 5+"], painPointSignals: ["Low outbound reply rates", "Pipeline efficiency declining"], sourceTemplateKey: "saas-eu-mm" },
  { companyName: "Gympass", contactName: "Lars Eriksen", title: "RevOps Manager", region: "Europe", industry: "SaaS", companySize: "Mid-Market", tags: ["wellness-tech", "global-sales"], traits: ["Uses Salesforce or HubSpot CRM", "Growing headcount in sales"], painPointSignals: ["Tool sprawl across sales stack", "SDR ramp time too long"], sourceTemplateKey: "saas-eu-mm" },

  // SaaS / Asia Pacific
  { companyName: "Canva", contactName: "Raj Mehta", title: "VP Sales", region: "Asia Pacific", industry: "SaaS", companySize: "Enterprise", tags: ["design-tools", "enterprise-motion", "high-growth"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Pipeline efficiency declining", "Low outbound reply rates"], sourceTemplateKey: "saas-apac-ent" },
  { companyName: "SafetyCulture", contactName: "Yuki Tanaka", title: "Head of Growth", region: "Asia Pacific", industry: "SaaS", companySize: "Mid-Market", tags: ["workplace-safety", "expanding-sales"], traits: ["Growing headcount in sales", "Recently raised Series A/B"], painPointSignals: ["SDR ramp time too long", "Low outbound reply rates"], sourceTemplateKey: "saas-apac-mm" },

  // Cybersecurity / North America
  { companyName: "CrowdStrike", contactName: "Brian Nakamura", title: "VP Sales", region: "North America", industry: "Cybersecurity", companySize: "Enterprise", tags: ["endpoint-security", "enterprise", "public-company"], traits: ["Handles sensitive customer data", "Subject to SOC2 / ISO 27001", "Multi-cloud infrastructure", "Growing engineering team"], painPointSignals: ["Compliance burden increasing", "Security team bandwidth constraints"], sourceTemplateKey: "cyber-na-ent" },
  { companyName: "SentinelOne", contactName: "Rachel Cooper", title: "CRO", region: "North America", industry: "Cybersecurity", companySize: "Enterprise", tags: ["ai-security", "outbound-heavy", "public-company"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Pipeline efficiency declining", "Low outbound reply rates", "Tool sprawl across sales stack"], sourceTemplateKey: "saas-na-ent" },
  { companyName: "Wiz", contactName: "Steven Chang", title: "VP Sales", region: "North America", industry: "Cybersecurity", companySize: "Mid-Market", tags: ["cloud-security", "series-d", "hyper-growth"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Recently raised Series A/B", "Growing headcount in sales"], painPointSignals: ["SDR ramp time too long", "Pipeline efficiency declining", "Low outbound reply rates"], sourceTemplateKey: "saas-na-mm" },

  // Fintech / Europe
  { companyName: "Revolut", contactName: "Oliver Graham", title: "Head of B2B Sales", region: "Europe", industry: "Fintech", companySize: "Enterprise", tags: ["neobank", "b2b-expansion", "high-growth"], traits: ["Uses outbound as primary GTM", "Growing headcount in sales", "Expanding to new markets"], painPointSignals: ["SDR ramp time too long", "Pipeline efficiency declining"], sourceTemplateKey: "fin-eu-ent" },
  { companyName: "Mollie", contactName: "Emma Richardson", title: "VP Sales", region: "Europe", industry: "Fintech", companySize: "Mid-Market", tags: ["payments", "series-c", "eu-focused"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Low outbound reply rates", "Tool sprawl across sales stack"], sourceTemplateKey: "fin-eu-mm" },

  // Additional diverse candidates
  { companyName: "Airtable", contactName: "Nicole Adams", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["productivity", "enterprise-motion", "series-f"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Pipeline efficiency declining", "Wasted outbound effort on bad-fit accounts"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Drata", contactName: "Eric Foster", title: "CRO", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["compliance", "outbound-heavy", "series-c"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Recently raised Series A/B", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Low outbound reply rates", "Poor lead-to-opportunity conversion", "SDR ramp time too long"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Grafana Labs", contactName: "David Okonkwo", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["observability", "open-source-saas", "series-d"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM", "Growing headcount in sales"], painPointSignals: ["Pipeline efficiency declining", "Low outbound reply rates", "Tool sprawl across sales stack"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Gusto", contactName: "Patricia Moore", title: "RevOps Manager", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["hr-tech", "smb-focused", "scaling-enterprise"], traits: ["Uses Salesforce or HubSpot CRM", "Growing headcount in sales", "Uses outbound as primary GTM"], painPointSignals: ["Wasted outbound effort on bad-fit accounts", "Pipeline efficiency declining"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Calendly", contactName: "Travis King", title: "Head of Growth", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["scheduling", "product-led-sales", "series-b"], traits: ["Recently raised Series A/B", "Growing headcount in sales", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Low outbound reply rates", "Poor lead-to-opportunity conversion"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Snyk", contactName: "Maya Gupta", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["dev-security", "enterprise-motion", "series-g"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Pipeline efficiency declining", "SDR ramp time too long", "Tool sprawl across sales stack"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Postman", contactName: "Henrik Olsen", title: "CRO", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["api-tools", "dev-first", "series-d"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Growing headcount in sales"], painPointSignals: ["Low outbound reply rates", "Pipeline efficiency declining"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Mixpanel", contactName: "Sarah Kim", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["analytics", "outbound-heavy"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Wasted outbound effort on bad-fit accounts", "Poor lead-to-opportunity conversion", "Tool sprawl across sales stack"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Supabase", contactName: "Amy Zhang", title: "Head of Growth", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["dev-tools", "open-source", "series-c"], traits: ["Recently raised Series A/B", "Growing headcount in sales"], painPointSignals: ["Low outbound reply rates", "SDR ramp time too long"], sourceTemplateKey: "saas-na-mm" },
  { companyName: "Ashby", contactName: "Victor Reyes", title: "VP Sales", region: "North America", industry: "SaaS", companySize: "Mid-Market", tags: ["ats", "series-c", "outbound-first"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Recently raised Series A/B", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Pipeline efficiency declining", "Low outbound reply rates", "Wasted outbound effort on bad-fit accounts"], sourceTemplateKey: "saas-na-mm" },

  // Slightly less fitting leads for variety
  { companyName: "Shopify", contactName: "George Harrison", title: "VP Partnerships", region: "North America", industry: "E-Commerce", companySize: "Enterprise", tags: ["ecommerce-platform", "public"], traits: ["Uses Salesforce or HubSpot CRM"], painPointSignals: ["Tool sprawl across sales stack"], sourceTemplateKey: "ecom-na-ent" },
  { companyName: "Stripe", contactName: "Frank Robinson", title: "VP Sales", region: "North America", industry: "Fintech", companySize: "Enterprise", tags: ["payments", "developer-first"], traits: ["Uses outbound as primary GTM", "Has SDR team of 5+", "Uses Salesforce or HubSpot CRM"], painPointSignals: ["Pipeline efficiency declining"], sourceTemplateKey: "fin-na-ent" },
  { companyName: "Plaid", contactName: "Sandra Lee", title: "Head of Growth", region: "North America", industry: "Fintech", companySize: "Mid-Market", tags: ["banking-api", "series-d"], traits: ["Growing headcount in sales", "Recently raised Series A/B"], painPointSignals: ["SDR ramp time too long"], sourceTemplateKey: "fin-na-mm" },
];
